import { ApplicationField, ApplicationPackage } from "./application.js";
import { OrgProfile } from "./types.js";

/**
 * Applicant-supplied values for the fields no profile can provide
 * (registration identifiers and the person legally authorised to sign).
 */
export interface ApplicantCredentials {
  uei?: string;
  ein?: string;
  aorName?: string;
  aorTitle?: string;
  aorEmail?: string;
  aorPhone?: string;
  congressionalDistrict?: string;
  street?: string;
  city?: string;
  state?: string;
  zip?: string;
  matchSource?: string;
}

export interface ValidationIssue {
  field: string;
  message: string;
  severity: "error" | "warning";
}

export interface SubmissionResult {
  ready: boolean;
  issues: ValidationIssue[];
  /** Grants.gov SF-424 XML, produced only when validation passes. */
  xml?: string;
  filename?: string;
  workspaceUrl: string;
  instructions: string[];
}

/** UEI: 12 alphanumeric chars, no I/O to avoid ambiguity with 1/0. */
const UEI_RE = /^[A-HJ-NP-Z0-9]{12}$/i;
/** EIN: NN-NNNNNNN */
const EIN_RE = /^\d{2}-?\d{7}$/;

function esc(s: unknown): string {
  return String(s ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

/**
 * Validates the assembled application against the rules Grants.gov itself
 * enforces at submission. Catching these here means the applicant fixes them
 * before a rejected upload, not after.
 */
export function validateSubmission(
  pkg: ApplicationPackage,
  creds: ApplicantCredentials
): ValidationIssue[] {
  const issues: ValidationIssue[] = [];

  if (!creds.uei?.trim()) {
    issues.push({ field: "uei", message: "UEI is required — register at SAM.gov to obtain one.", severity: "error" });
  } else if (!UEI_RE.test(creds.uei.trim())) {
    issues.push({ field: "uei", message: "UEI must be 12 alphanumeric characters (letters I and O are not used).", severity: "error" });
  }

  if (!creds.ein?.trim()) {
    issues.push({ field: "ein", message: "EIN / Taxpayer ID is required.", severity: "error" });
  } else if (!EIN_RE.test(creds.ein.trim())) {
    issues.push({ field: "ein", message: "EIN must be 9 digits, formatted NN-NNNNNNN.", severity: "error" });
  }

  if (!creds.aorName?.trim()) {
    issues.push({ field: "aorName", message: "An Authorized Organization Representative must be named.", severity: "error" });
  }
  if (!creds.aorEmail?.trim()) {
    issues.push({ field: "aorEmail", message: "AOR email is required for the agency to contact your organization.", severity: "error" });
  }
  if (!creds.congressionalDistrict?.trim()) {
    issues.push({ field: "congressionalDistrict", message: "Congressional district is required (format: CA-12).", severity: "error" });
  }

  // Deadline check — submitting after close is an automatic rejection.
  if (pkg.responseDate) {
    const due = new Date(pkg.responseDate);
    if (!Number.isNaN(due.getTime()) && due.getTime() < Date.now()) {
      issues.push({ field: "deadline", message: `This opportunity closed on ${pkg.responseDate}. It can no longer be submitted.`, severity: "error" });
    }
  }

  if (pkg.costSharingRequired && !creds.matchSource?.trim()) {
    issues.push({
      field: "matchSource",
      message: "This opportunity requires cost sharing — identify the source and amount of your match.",
      severity: "error",
    });
  }

  // Narrative gaps block a credible submission but are the applicant's call.
  const unresolved = pkg.requiresHumanInput.filter(
    (r) => !/UEI|EIN|Taxpayer|Authorized Representative|Congressional District|matching funds/i.test(r)
  );
  for (const item of unresolved) {
    issues.push({ field: "narrative", message: `Unresolved: ${item}`, severity: "warning" });
  }

  return issues;
}

/**
 * Emits a Grants.gov-style SF-424 XML document. This is the artifact the
 * applicant uploads into their own authenticated Workspace — GrantWeave never
 * transmits it, because federal submission legally requires AOR certification.
 */
export function buildSF424Xml(
  pkg: ApplicationPackage,
  org: OrgProfile,
  creds: ApplicantCredentials
): string {
  const field = (key: string): string => pkg.fields.find((f: ApplicationField) => f.key === key)?.value || "";

  return `<?xml version="1.0" encoding="UTF-8"?>
<!--
  SF-424 Application for Federal Assistance
  Generated by GrantWeave for upload into a Grants.gov Workspace.
  NOT a submission: it must be certified and submitted by the AOR named below.
-->
<grant:GrantApplication
    xmlns:grant="http://apply.grants.gov/system/MetaGrantApplication"
    xmlns:SF424="http://apply.grants.gov/forms/SF424_4_0-V4.0">
  <grant:Forms>
    <SF424:SF424_4_0>
      <SF424:SubmissionType>Application</SF424:SubmissionType>
      <SF424:ApplicationType>New</SF424:ApplicationType>

      <SF424:FundingOpportunityNumber>${esc(pkg.opportunityNumber)}</SF424:FundingOpportunityNumber>
      <SF424:FundingOpportunityTitle>${esc(pkg.opportunityTitle)}</SF424:FundingOpportunityTitle>
      <SF424:CFDANumber>${esc(pkg.cfdaNumbers.join(", "))}</SF424:CFDANumber>

      <SF424:Applicant>
        <SF424:OrganizationName>${esc(org.name || field("applicantName"))}</SF424:OrganizationName>
        <SF424:UEI>${esc(creds.uei)}</SF424:UEI>
        <SF424:EmployerTaxpayerIdentificationNumber>${esc(creds.ein)}</SF424:EmployerTaxpayerIdentificationNumber>
        <SF424:Address>
          <SF424:Street1>${esc(creds.street)}</SF424:Street1>
          <SF424:City>${esc(creds.city)}</SF424:City>
          <SF424:State>${esc(creds.state)}</SF424:State>
          <SF424:ZipPostalCode>${esc(creds.zip)}</SF424:ZipPostalCode>
          <SF424:Country>USA</SF424:Country>
        </SF424:Address>
        <SF424:CongressionalDistrict>${esc(creds.congressionalDistrict)}</SF424:CongressionalDistrict>
        <SF424:ApplicantTypeCode>${esc(field("applicantType"))}</SF424:ApplicantTypeCode>
      </SF424:Applicant>

      <SF424:Project>
        <SF424:ProjectTitle>${esc(field("projectTitle"))}</SF424:ProjectTitle>
        <SF424:AreasAffected>${esc(field("projectAreas"))}</SF424:AreasAffected>
        <SF424:ProjectDescription>${esc(pkg.narrative.projectAbstract)}</SF424:ProjectDescription>
      </SF424:Project>

      <SF424:EstimatedFunding>
        <SF424:FederalAmount>${esc(field("fundingRequested").replace(/[^0-9.]/g, ""))}</SF424:FederalAmount>
        <SF424:MatchSource>${esc(creds.matchSource)}</SF424:MatchSource>
      </SF424:EstimatedFunding>

      <SF424:AuthorizedRepresentative>
        <SF424:Name>${esc(creds.aorName)}</SF424:Name>
        <SF424:Title>${esc(creds.aorTitle)}</SF424:Title>
        <SF424:Email>${esc(creds.aorEmail)}</SF424:Email>
        <SF424:Phone>${esc(creds.aorPhone)}</SF424:Phone>
        <SF424:SignatureStatus>PENDING_AOR_CERTIFICATION</SF424:SignatureStatus>
      </SF424:AuthorizedRepresentative>
    </SF424:SF424_4_0>
  </grant:Forms>

  <grant:Attachments>
    <grant:ProjectNarrative>
      <grant:StatementOfNeed>${esc(pkg.narrative.statementOfNeed)}</grant:StatementOfNeed>
      <grant:Approach>${esc(pkg.narrative.approach)}</grant:Approach>
      <grant:BudgetNarrative>${esc(pkg.narrative.budgetNarrative)}</grant:BudgetNarrative>
      <grant:ExpectedOutcomes>
${pkg.narrative.expectedOutcomes.map((o) => `        <grant:Outcome>${esc(o)}</grant:Outcome>`).join("\n")}
      </grant:ExpectedOutcomes>
    </grant:ProjectNarrative>
  </grant:Attachments>
</grant:GrantApplication>
`;
}

export function prepareSubmission(
  pkg: ApplicationPackage,
  org: OrgProfile,
  creds: ApplicantCredentials
): SubmissionResult {
  const issues = validateSubmission(pkg, creds);
  const blocking = issues.filter((i) => i.severity === "error");
  const ready = blocking.length === 0;

  const workspaceUrl = pkg.oppId
    ? `https://www.grants.gov/search-results-detail/${encodeURIComponent(pkg.oppId)}`
    : "https://www.grants.gov/applicants/workspace-overview";

  return {
    ready,
    issues,
    xml: ready ? buildSF424Xml(pkg, org, creds) : undefined,
    filename: ready ? `SF424-${(pkg.opportunityNumber || pkg.grantId).replace(/[^\w-]/g, "_")}.xml` : undefined,
    workspaceUrl,
    instructions: [
      "Sign in to Grants.gov with your organization's account (the one linked to your SAM.gov registration).",
      "Open the opportunity and create a Workspace for it.",
      "Upload the generated SF-424 XML into the Workspace forms section.",
      "Attach any documents the agency requires that are not covered here (letters of support, budget spreadsheets).",
      "Have your Authorized Organization Representative review, certify, and click Submit in Grants.gov.",
    ],
  };
}
