import { jsPDF } from "jspdf";
import type { Organization } from "@/types";

export function generateExecutiveFactsheetPdf(organization?: Organization) {
  const doc = new jsPDF();
  const orgName = organization?.name || "Organization Strategy Brief";
  const mission = organization?.mission || "Dedicated to advancing high-impact societal initiatives.";
  const focusAreas = (organization?.focusAreas || ["Climate", "Education", "Public Health"]).join(", ");

  doc.setFillColor(15, 23, 42); // zinc-950
  doc.rect(0, 0, 210, 297, "F");

  // Emerald Title
  doc.setTextColor(16, 185, 129); // emerald-500
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text("GrantWeave Executive Factsheet", 20, 25);

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(14);
  doc.text(orgName, 20, 36);

  doc.setLineWidth(0.5);
  doc.setDrawColor(255, 255, 255, 0.2);
  doc.line(20, 42, 190, 42);

  // Mission
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(16, 185, 129);
  doc.text("MISSION & VISION", 20, 52);

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(200, 200, 200);
  const missionLines = doc.splitTextToSize(mission, 170);
  doc.text(missionLines, 20, 60);

  // Funding Pipeline Summary
  let y = 60 + missionLines.length * 6 + 10;
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(16, 185, 129);
  doc.text("FUNDING STRATEGY & TARGET PIPELINE", 20, y);

  y += 8;
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(255, 255, 255);
  doc.text(`Primary Focus Areas: ${focusAreas}`, 20, y);

  y += 6;
  doc.text(`Target Grant Range: ${organization?.minGrant || "$50k"} - ${organization?.maxGrant || "$300k"}`, 20, y);

  y += 6;
  doc.text(`Operating Regions: ${(organization?.regions || ["United States"]).join(", ")}`, 20, y);

  // Active Grants Table
  y += 14;
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(16, 185, 129);
  doc.text("MATCHED GRANT OPPORTUNITIES", 20, y);

  const grants = [
    { title: "NIH Research Innovation Grant", amount: "$250,000", match: "92%", deadline: "Sep 30, 2026" },
    { title: "EU Horizon Climate Solutions Fund", amount: "$180,000", match: "88%", deadline: "Oct 15, 2026" },
    { title: "NSF STEM Education Excellence Award", amount: "$95,000", match: "95%", deadline: "Nov 01, 2026" },
  ];

  y += 8;
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(160, 160, 160);
  doc.text("Grant Opportunity", 20, y);
  doc.text("Target Budget", 110, y);
  doc.text("Match Score", 145, y);
  doc.text("Deadline", 170, y);

  y += 4;
  doc.setDrawColor(255, 255, 255, 0.1);
  doc.line(20, y, 190, y);

  y += 6;
  doc.setFont("helvetica", "normal");
  doc.setTextColor(255, 255, 255);

  grants.forEach((g) => {
    doc.text(g.title.length > 40 ? g.title.substring(0, 38) + "…" : g.title, 20, y);
    doc.text(g.amount, 110, y);
    doc.setTextColor(16, 185, 129);
    doc.text(g.match, 145, y);
    doc.setTextColor(255, 255, 255);
    doc.text(g.deadline, 170, y);
    y += 8;
  });

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(100, 100, 100);
  doc.text("Generated by GrantWeave AI Intelligence Swarm", 20, 280);

  doc.save(`${orgName.toLowerCase().replace(/\s+/g, "_")}_executive_factsheet.pdf`);
}
